/**
 *     This file is part of Diki.
 *
 *     Copyright (C) 2009 jtheuer
 *     Please refer to the documentation for a complete list of contributors
 *
 *     Diki is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     Diki is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with Diki.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.jtheuer.diki.gui.actions;

import java.awt.event.ActionEvent;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.AbstractAction;

import de.jtheuer.diki.gui.Messages;
import de.jtheuer.diki.gui.utils.Log;
import de.jtheuer.diki.lib.NetworkConnection;
import de.jtheuer.diki.lib.connectors.ConnectorException;

/**
 * @author Jan Torben Heuer <jan.heuer@uni-muenster.de>
 * 
 */
public class ExportAction extends AbstractAction {
	/** generated */
	private static final long serialVersionUID = 2588216215976940413L;
	/* automatically generated Logger */@SuppressWarnings("unused") //$NON-NLS-1$
	private static final Logger LOGGER = Logger.getLogger(ExportAction.class.getName());
	private final NetworkConnection networkConnection;

	/**
	 * 
	 */
	public ExportAction(NetworkConnection connection) {
		super(Messages.getString("ExportAction.1")); //$NON-NLS-1$
		this.networkConnection = connection;
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		try {
			File file = File.createTempFile("sesamerdf", ".xml"); //$NON-NLS-1$ //$NON-NLS-2$
			FileWriter fw = new FileWriter(file);
			networkConnection.getSesame().exportDatabase(fw);
			Log.info(Messages.getString("ExportAction.4") + file.getAbsolutePath()); //$NON-NLS-1$
		} catch (IOException e1) {
			LOGGER.log(Level.SEVERE, "autogenerated catch-block", e1); //$NON-NLS-1$
		} catch (ConnectorException e2) {
			LOGGER.log(Level.SEVERE, "autogenerated catch-block", e2); //$NON-NLS-1$
		}
	}

}
