/**
 *     This file is part of Diki.
 *
 *     Copyright (C) 2009 jtheuer
 *     Please refer to the documentation for a complete list of contributors
 *
 *     Diki is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     Diki is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with Diki.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
    (c) by Jan Torben Heuer <jan.heuer@uni-muenster.de

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/
 */
package de.jtheuer.diki.gui.utils;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import de.jtheuer.diki.gui.Main;

/**
 * 
 */
public class Log {
	/* autogenerated Logger */@SuppressWarnings("unused")
	private final static Logger LOGGER = Logger.getLogger("diki logger");
	
	public static void error(String msg) {
		JOptionPane.showMessageDialog(null, msg, Main.APPLICATION_TITLE	, JOptionPane.ERROR_MESSAGE);
	}
	
	public static void error(Throwable t) {
		LOGGER.log(Level.SEVERE, "", t);
		error(t.getMessage());
	}

	public static void info(String msg) {
		JOptionPane.showMessageDialog(null, msg, Main.APPLICATION_TITLE	, JOptionPane.INFORMATION_MESSAGE);
	}
	
	private static void showMessage(final String msg, final int type) {
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				JOptionPane.showMessageDialog(null, msg, Main.APPLICATION_TITLE	, type);
			}
		});
	}

	public static void debug(String string) {
		LOGGER.fine(string);
	}
	
	public static void debug(Throwable t) {
		LOGGER.log(Level.INFO, "", t);
	}
	
}
